### PR TITLE
talk.c

### PR DESCRIPTION
**Pull request by minirop**
This PR isn't meant to be merged yet, but to get feedback as a whole.

For instance, I don't know if those `<< 0x18` are meant to be something else. I tried things like `== 0x01000000` but that doesn't match.
Another note, I'm guessing `0x1234` is `MSG_1234` but including `constants/msg.h` triggers the text processing script which ends up with `duplicate symbol gMsgTable` and I didn't want to edit more files than necessary.

### CODE REVIEW

**Comment by MokhaLeee** [comment]
It means it's judging on a `s8`, here `if (IsTalkLocked() << 0x18)` can be directly writen as `if (IsTalkLocked())`

```
lsl r0, #0x18
cmp r0, #0
```

r0 is `s8`, or say, [`bool`](https://github.com/MokhaLeee/FireEmblem7J/blob/main/include/gbafe/types.h#L7)

```
lsl r0, #0x18
lsr r0, #0x18
```
r0 is `u8`

```
lsl r0, #0x18
asr r0, #0x18
```
r0 is `s8`

It is recommanded to see:

1. [fe8u contributing note](https://github.com/laqieer/fireemblem8u/blob/remove_tools/CONTRIBUTING.md)
2. some [fe6 decomp](https://github.com/MokhaLeee/fe6/tree/main/docs) doc by @StanHash
3. [pret/asm2c](https://discord.com/channels/442462691542695948/597616808023031819) channel in discard
4. [feu/decomp](https://discord.com/channels/144670830150811649/416236460002377730) channel in discard
5. refer to the same part of code in [fe6 talk](https://github.com/FireEmblemUniverse/fireemblem8u/blob/master/src/scene.c) and [fe8u talk](https://github.com/MokhaLeee/fe6/blob/main/src/talk.c)

**Comment by MokhaLeee** [comment]
as for MSG, this is a WIP work, for not don't include that file.
I may fix this issue in main branch

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/FireEmblem7J/commit/4aeea2fc9005787bc53011484ff4de97c9f9fe42

**Comment by MokhaLeee** [comment]
https://github.com/MokhaLeee/FireEmblem7J/commit/4aeea2fc9005787bc53011484ff4de97c9f9fe42

**Comment by MokhaLeee** [comment]
is this pt ready for merging?

**Comment by minirop** [comment]
not yet. I'll try to do the entire file. (then it will need some cleanup)

**Comment by minirop** [comment]
I think I'm *done* for now, I'm kinda stuck. This is what's remaining

### sub_8007C10 & sub_8007C48

I couldn't find a type that would make them match, so I made my own.

### sub_80080A8

Unknown symbol at address 0x0202BC35.

### sub_8009834 & SetTalkFaceDisp

Need to set the address of their local array to the correct address.

### sub_800821C, sub_80096E0 & sub_8009AA8

sub_8009AA8 has adds r0, r1, r6 instead of adds r0, r6, r1
sub_800821C and sub_80096E0 are missing an instruction that doesn't seem to do anything.

### TalkInterpret, sub_8009920 & PrintStringToTexts

Big functions. I tried but didn't go anywhere. I leave them for now in case someone wants to tackle them.

**Comment by MokhaLeee** [comment]
nice job

**Pull request merged**
